services:
  - type: web
    name: waste-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements-prod.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    plan: free
    healthCheckPath: /
    autoDeploy: true
